const CART_KEY="pcforge_cart";const BUILD_KEY="pcforge_build";
const money=n=>new Intl.NumberFormat("vi-VN").format(n)+" ₫";
function getCart(){try{return JSON.parse(localStorage.getItem(CART_KEY))||[]}catch{return[]}}
function saveCart(cart){localStorage.setItem(CART_KEY,JSON.stringify(cart));updateCartBadge()}
function updateCartBadge(){const el=document.getElementById("cartBadge");if(el)el.textContent=getCart().reduce((s,i)=>s+i.quantity,0)}
function addToCart(product,quantity=1){const cart=getCart();const found=cart.find(i=>i.id===product.id);if(found)found.quantity+=quantity;else cart.push({id:product.id,quantity});saveCart(cart);showToast("Đã thêm sản phẩm vào giỏ hàng!","success")}
function showToast(message,type="success"){let box=document.getElementById("toast-container");if(!box){box=document.createElement("div");box.id="toast-container";document.body.appendChild(box)}const el=document.createElement("div");el.className="toast "+type;el.textContent=message;box.appendChild(el);setTimeout(()=>el.remove(),2600)}
function productIcon(category){return categoryIcons[category]||"▣"}
function productCard(p){let badge=p.isSale?'<span class="product-badge sale">SALE</span>':p.isHot?'<span class="product-badge hot">HOT</span>':p.isNew?'<span class="product-badge">NEW</span>':"";const image=p.image?`<img src="${p.image}" alt="${p.name}">`:`<div class="product-placeholder">${productIcon(p.category)}</div>`;return `<article class="product-card">${badge}<a href="product-detail.html?id=${p.id}"><div class="product-img">${image}</div></a><span class="product-brand">${p.brand}</span><h3>${p.name}</h3><div class="rating">★★★★★ <span>(${p.rating})</span></div><div class="price">${money(p.price)} ${p.oldPrice?`<span class="old-price">${money(p.oldPrice)}</span>`:""}</div><div class="product-actions"><a class="btn btn-outline" href="product-detail.html?id=${p.id}">Xem chi tiết</a><button class="cart-icon-btn" data-add="${p.id}" aria-label="Thêm vào giỏ">🛒</button></div></article>`}
function bindProductButtons(root=document){root.querySelectorAll("[data-add]").forEach(btn=>btn.addEventListener("click",()=>{const p=products.find(x=>x.id==btn.dataset.add);if(p)addToCart(p)}))}
function renderProductsInto(id,list){const el=document.getElementById(id);if(el){el.innerHTML=list.map(productCard).join("");bindProductButtons(el)}}
function renderCategories(){const el=document.getElementById("categoryStrip");if(!el)return;el.innerHTML=categories.map(c=>`<a class="category-item" href="products.html?category=${encodeURIComponent(c)}"><div class="category-icon">${categoryIcons[c]}</div><strong>${c}</strong></a>`).join("")}
function renderMiniBuild(){const el=document.getElementById("miniBuildList");if(!el)return;let build={};try{build=JSON.parse(localStorage.getItem(BUILD_KEY))||{}}catch{};el.innerHTML=builderCategories.slice(0,8).map(c=>{const p=products.find(x=>x.id===build[c]);return `<div class="mini-slot"><div class="slot-icon">${categoryIcons[c]}</div><div><strong>${c}</strong><small>${p?p.name:"Chưa chọn"}</small></div><span>›</span></div>`}).join("");const total=Object.values(build).reduce((s,id)=>s+(products.find(p=>p.id===id)?.price||0),0);const totalEl=document.getElementById("miniBuildTotal");if(totalEl)totalEl.textContent=money(total)}
function initHome(){renderCategories();renderProductsInto("newProducts",products.filter(p=>p.isNew).slice(0,4));renderProductsInto("hotProducts",products.filter(p=>p.isHot).slice(0,4));renderProductsInto("saleProducts",products.filter(p=>p.isSale).slice(0,4));renderMiniBuild();updateCartBadge();startCountdown()}
function startCountdown(){const el=document.getElementById("countdown");if(!el)return;let end=localStorage.getItem("pcforge_sale_end");if(!end){end=Date.now()+1000*60*60*15;localStorage.setItem("pcforge_sale_end",end)}function tick(){let diff=Math.max(0,Number(end)-Date.now());const d=Math.floor(diff/86400000),h=Math.floor(diff/3600000)%24,m=Math.floor(diff/60000)%60,s=Math.floor(diff/1000)%60;if(diff===0){el.innerHTML="<strong>SALE ENDED</strong>";return}el.innerHTML=`<span><b>${String(d).padStart(2,"0")}</b><small>Ngày</small></span><span><b>${String(h).padStart(2,"0")}</b><small>Giờ</small></span><span><b>${String(m).padStart(2,"0")}</b><small>Phút</small></span><span><b>${String(s).padStart(2,"0")}</b><small>Giây</small></span>`}tick();setInterval(tick,1000)}
function initGlobalSearch(){const input=document.getElementById("globalSearch"),btn=document.getElementById("globalSearchBtn");if(!input)return;const go=()=>{const q=input.value.trim();location.href="products.html"+(q?"?q="+encodeURIComponent(q):"")};btn?.addEventListener("click",go);input.addEventListener("keydown",e=>{if(e.key==="Enter")go()})}
document.addEventListener("DOMContentLoaded",()=>{updateCartBadge();initGlobalSearch();const menu=document.getElementById("mobileMenuBtn"),nav=document.getElementById("mainNav");menu?.addEventListener("click",()=>nav?.classList.toggle("open"));if(document.getElementById("newProducts"))initHome()});